DROP DATABASE IF EXISTS Javagotchi;
CREATE DATABASE Javagotchi CHARACTER SET utf8mb4;
USE Javagotchi;

CREATE TABLE IF NOT EXISTS USUARIO (
	username VARCHAR(30) NOT NULL,
	contrasenia VARCHAR(30) NOT NULL,
	nombre_completo VARCHAR(120) NOT NULL,
	email VARCHAR(100) NOT NULL,
	fecha_nac DATE NOT NULL,
	ciudad VARCHAR(50) NOT NULL,
	fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
	CONSTRAINT PRIMARY KEY (username),
    CONSTRAINT UC_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS TIPO_MASCOTA (
	tipo_mascota VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMARY KEY (tipo_mascota)
);

CREATE TABLE IF NOT EXISTS MASCOTA (
	id_mascota INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(30) NOT NULL,
    username_duenio VARCHAR(30) NOT NULL,
    tipo_mascota VARCHAR(20) NOT NULL,
    color ENUM('ROJO', 'VERDE', 'AMARILLO', 'AZUL', 'MORADO', 'CIAN') NOT NULL,
    sexo ENUM('MACHO', 'HEMBRA') NOT NULL,
    fecha_creacion DATE NOT NULL DEFAULT (CURRENT_DATE),
    nutricion INT UNSIGNED NOT NULL CHECK (nutricion <= 10) DEFAULT 5,
    limpieza INT UNSIGNED NOT NULL CHECK (limpieza <= 10) DEFAULT 5,
    felicidad INT UNSIGNED NOT NULL CHECK (felicidad <= 10) DEFAULT 5,
    CONSTRAINT PRIMARY KEY (id_mascota),
    CONSTRAINT FK_duenioMascota FOREIGN KEY (username_duenio) REFERENCES USUARIO(username) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_tipoMascota FOREIGN KEY (tipo_mascota) REFERENCES TIPO_MASCOTA(tipo_mascota) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS COMIDA (
	cod_comida VARCHAR(20) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    tipo_mascota VARCHAR(20) NOT NULL,
    nutricion_aportada INT UNSIGNED NOT NULL,
    felicidad_aportada INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY (cod_comida),
    CONSTRAINT FK_tipoMascotaComida FOREIGN KEY (tipo_mascota) REFERENCES TIPO_MASCOTA(tipo_mascota) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS JUEGO (
	cod_juego VARCHAR(20) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    tipo_mascota VARCHAR(20) NOT NULL,
    nutricion_disminuida INT UNSIGNED NOT NULL,
    limpieza_disminuida INT UNSIGNED NOT NULL,
    felicidad_aportada INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY (cod_juego),
    CONSTRAINT FK_tipoMascotaJuego FOREIGN KEY (tipo_mascota) REFERENCES TIPO_MASCOTA(tipo_mascota) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS REGISTRO_ALIMENTACION (
	cod_comida VARCHAR(20) NOT NULL,
    id_mascota INT UNSIGNED NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PRIMARY KEY (cod_comida, id_mascota, fecha_hora),
    CONSTRAINT FK_regAlimentComida FOREIGN KEY (cod_comida) REFERENCES COMIDA(cod_comida) ON UPDATE CASCADE,
    CONSTRAINT FK_regAlimentMascota FOREIGN KEY (id_mascota) REFERENCES MASCOTA(id_mascota) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REGISTRO_JUEGO (
	cod_juego VARCHAR(20) NOT NULL,
    id_mascota INT UNSIGNED NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PRIMARY KEY (cod_juego, id_mascota, fecha_hora),
    CONSTRAINT FK_regJuego FOREIGN KEY (cod_juego) REFERENCES JUEGO(cod_juego) ON UPDATE CASCADE,
    CONSTRAINT FK_regJuegoMascota FOREIGN KEY (id_mascota) REFERENCES MASCOTA(id_mascota) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REGISTRO_LIMPIEZA (
	id_mascota INT UNSIGNED NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    felicidad_aportada INT UNSIGNED NOT NULL DEFAULT 2,
    CONSTRAINT PRIMARY KEY (id_mascota, fecha_hora),
    CONSTRAINT FK_regLimpiaMascota FOREIGN KEY (id_mascota) REFERENCES MASCOTA(id_mascota) ON UPDATE CASCADE ON DELETE CASCADE
);